---
title: "compare-data"
output: 
  rmarkdown::html_vignette:
    toc: yes
    toc_depth: 3
    df_print: kable
vignette: >
  %\VignetteIndexEntry{compare-data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>", 
  error = TRUE
)
options(
  rmarkdown.html_vignette.check_title = FALSE,
  tibble.print_max = Inf)
```

```{r pkgs, message=FALSE, warning=FALSE}
library(dfdiffs)
library(openxlsx)
library(janitor) 
library(arsenal) # comparedf
library(diffdf)  # diffdf
library(dplyr)
library(tidyr)
library(stringr)
library(lubridate)
library(forcats)
library(glue)
library(purrr)
library(vroom)
library(reactable)
library(haven)
library(readxl)
```


# Motivation

The goal of the `dfdiffs` is to answer the following questions: 

1. What rows are here now that weren't here before?  
2. What rows were here before that aren't here now?   
3. What values have been changed?

## Test data 

These are two Masters tables from the [Lahman baseball database.](https://www.seanlahman.com/baseball-archive/statistics/) 

```{r masters}
m15 <- dfdiffs::master15 |> 
  dplyr::slice_sample(n = 3000, replace = FALSE)
max(m15$debut, na.rm = TRUE)
m20 <- dfdiffs::master20 |> 
  dplyr::slice_sample(n = 3000, replace = FALSE)
max(m20$debut, na.rm = TRUE)
```

## The `compare_data()` function 

```{r compare_data-args, eval=FALSE}
compare_data(compare = , base = , by = , by_col = , cols = )
```

```{r compare_data, echo=FALSE, eval=FALSE}
compare_data <- function(compare, base, by = NULL, by_col = NULL, cols = NULL) {
  
  new_data <- create_new_data(
    compare = compare, base = base, by = by, by_col = by_col, cols = cols)
  
  deleted_data <- create_deleted_data(
    compare = compare, base = base, by = by, by_col = by_col, cols = cols)
  
  changed_data <- create_changed_data(
    compare = compare, base = base, by = by, by_col = by_col, cols = cols)
  
  changed_num_diffs <- changed_data$num_diffs
  changed_var_diffs <- changed_data$var_diffs
  
  return(list(
    'new_data' = new_data,
    'deleted_data' = deleted_data,
    'changed_num_diffs' = changed_num_diffs,
    'changed_var_diffs' = changed_var_diffs
  ))
}
```

```{r test-compare_data}
comparisons <- compare_data(
  compare = m20, base = m15, 
  by = "playerID", by_col = "join", 
  cols = c("nameFirst", "nameLast", "nameGiven", "height"))
names(comparisons)
```


## `$new_data`

```{r new_data, eval=FALSE}
comparisons$new_data
```

```{r , echo=FALSE}
knitr::kable(head(comparisons$new_data), caption = "head(comparisons$new_data)") |> 
  kableExtra::kable_paper()
```


## `$deleted_data`

```{r deleted_data, eval=FALSE}
comparisons$deleted_data
```

```{r , echo=FALSE}
knitr::kable(head(comparisons$deleted_data), 
  caption = "head(comparisons$deleted_data)") |> 
  kableExtra::kable_paper()
```


## `$changed_num_diffs`

```{r changed_num_diffs, eval=FALSE}
comparisons$changed_num_diffs
```

```{r , echo=FALSE}
knitr::kable(comparisons$changed_num_diffs, 
  caption = "comparisons$changed_num_diffs") |> 
  kableExtra::kable_paper()
```


## `$changed_var_diffs`

```{r changed_var_diffs, eval=FALSE}
comparisons$changed_var_diffs
```

```{r , echo=FALSE}
knitr::kable(comparisons$changed_var_diffs, 
  caption = "comparisons$changed_var_diffs") |> 
  kableExtra::kable_paper()
```

