---
title: "Getting Started"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Getting Started

Quick dataset comparisons in three steps! 

#### 1) Upload 

+ Start by uploading a `base` (i.e., target) data file in the upload box 

+ After uploading the file, provide a name for the imported file (**uploaded files will not be imported into the application until they are named.**)

+ Repeat this process for the `compare` (i.e., comparison) dataset. 

#### 2) Select 

+ Click on the **Select Data** tab and review your uploaded data. If you'd like, you can reduce the columns you'd like to include in the comparison

+ In the **Select Join Columns** box, you'll see a table of shared columns between `base` and `compare` (f the data has a join column (or columns), you can select them in the **Select Joining Column(s)** section)

+ Use the final two boxes to review the data that will be compared

#### 3) Compare

+ After you've uploaded and selected the data, click on the **Compare Data** tab where you will see an info box summary of the two comparison datasets

+ The comparison outputs are displayed in three boxes: **New Data**, **Deleted Data**, and **Changed Data** 

